"""Initial migration

Revision ID: 88f471526532
Revises: 
Create Date: 2025-05-26 15:35:28.830121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f471526532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_btc_date_desc', 'btc_data', ['date'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_btc_data_date'), 'btc_data', ['date'], unique=True)
    op.create_index(op.f('ix_btc_data_id'), 'btc_data', ['id'], unique=False)
    op.create_table('volume_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price_change_pct', sa.Float(), nullable=False),
    sa.Column('volume_change_pct', sa.Float(), nullable=False),
    sa.Column('volume_follows_price', sa.String(), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_date_desc', 'volume_analysis', ['date'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_volume_analysis_date'), 'volume_analysis', ['date'], unique=False)
    op.create_index(op.f('ix_volume_analysis_id'), 'volume_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_analysis_id'), table_name='volume_analysis')
    op.drop_index(op.f('ix_volume_analysis_date'), table_name='volume_analysis')
    op.drop_index('idx_analysis_date_desc', table_name='volume_analysis', postgresql_using='btree')
    op.drop_table('volume_analysis')
    op.drop_index(op.f('ix_btc_data_id'), table_name='btc_data')
    op.drop_index(op.f('ix_btc_data_date'), table_name='btc_data')
    op.drop_index('idx_btc_date_desc', table_name='btc_data', postgresql_using='btree')
    op.drop_table('btc_data')
    # ### end Alembic commands ###
